///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adult_Slider02 recording.
    /// </summary>
    [TestModule("31168229-8652-455e-a3f8-671cecbf22e1", ModuleType.Recording, 1)]
    public partial class Adult_Slider02 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Adult_Slider02 instance = new Adult_Slider02();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adult_Slider02()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adult_Slider02 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult' at 29;14.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Adult.Click("29;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1907;88.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(4));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1907;88");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1919;694.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(5));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1919;694");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/b169d1a8-a600-4488-b892-2033e6f83b8f/video_placeholder_streaming_video.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-b169d1a8-a600-4488-b892-2033e6f83b8f-lRhwvtQ') on item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.HttpWwwHearyourwayComWpsWcmConne1'.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.HttpWwwHearyourwayComWpsWcmConne1Info, new RecordItemIndex(6));
            //Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.HttpWwwHearyourwayComWpsWcmConne1Info, "Src", "http://www.hearyourway.com/wps/wcm/connect/b169d1a8-a600-4488-b892-2033e6f83b8f/video_placeholder_streaming_video.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-b169d1a8-a600-4488-b892-2033e6f83b8f-lRhwvtQ");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag' at 8;13.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTagInfo, new RecordItemIndex(7));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag.Click("8;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag1' at 10;10.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag1Info, new RecordItemIndex(8));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag1.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag2' at 6;10.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag2Info, new RecordItemIndex(9));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag2.Click("6;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag3' at 5;9.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag3Info, new RecordItemIndex(10));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag3.Click("5;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag4' at 4;11.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag4Info, new RecordItemIndex(11));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag4.Click("4;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 39;30.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(12));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("39;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 38;30.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(13));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("38;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 38;30.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(14));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("38;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 38;30.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(15));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("38;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 38;30.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(16));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("38;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 15;24.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(17));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("15;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 18;24.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(18));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("18;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 18;24.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(19));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("18;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 18;24.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(20));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("18;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.BtnPlay' at 50;64.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.BtnPlayInfo, new RecordItemIndex(21));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.BtnPlay.Click("50;64");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus'.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(22));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus1' at 42;80.", repo.CochlearImplantSoundProcessorNucleus1.SelfInfo, new RecordItemIndex(23));
            repo.CochlearImplantSoundProcessorNucleus1.Self.Click("42;80");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(24));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
