///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adult_Content recording.
    /// </summary>
    [TestModule("f81b64c6-b3f7-45df-9567-2aea5d9e9772", ModuleType.Recording, 1)]
    public partial class Adult_Content : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Adult_Content instance = new Adult_Content();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adult_Content()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adult_Content Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult' at 24;9.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Adult.Click("24;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/12d1eea2-0ea5-469a-8e0c-13552cccaa62/HearYourWay_1024px.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-12d1eea2-0ea5-469a-8e0c-13552cccaa62-lN21Dkn') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConneInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConneInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/12d1eea2-0ea5-469a-8e0c-13552cccaa62/HearYourWay_1024px.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-12d1eea2-0ea5-469a-8e0c-13552cccaa62-lN21Dkn");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButton' at 33;22.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButtonInfo, new RecordItemIndex(5));
            repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButton.Click("33;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1910;162.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(6));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1910;162");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1910;272.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(7));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1910;272");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheWorldsFirstAndOnlyM'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheWorldsFirstAndOnlyMInfo, new RecordItemIndex(8));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheWorldsFirstAndOnlyMInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp1Info, new RecordItemIndex(9));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheApp'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo, new RecordItemIndex(10));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheApp' at 89;22.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo, new RecordItemIndex(11));
            repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheApp.Click("89;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearHearingImplantsCochlearUni.SpanTagNucleu'.", repo.CochlearHearingImplantsCochlearUni.SpanTagNucleuInfo, new RecordItemIndex(12));
            Validate.Exists(repo.CochlearHearingImplantsCochlearUni.SpanTagNucleuInfo);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus1' at 486;27.", repo.CochlearImplantSoundProcessorNucleus1.SelfInfo, new RecordItemIndex(13));
            //repo.CochlearImplantSoundProcessorNucleus1.Self.Click("486;27");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TheNucleusRSmartAppInteractiveDemo' at 486;29.", repo.TheNucleusRSmartAppInteractiveDemo.SelfInfo, new RecordItemIndex(14));
            repo.TheNucleusRSmartAppInteractiveDemo.Self.Click("486;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp1Info, new RecordItemIndex(15));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1904;248.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(16));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1904;248");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1906;382.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(17));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1906;382");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.At20PercentSmallerThanAMajorCompet'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.At20PercentSmallerThanAMajorCompetInfo, new RecordItemIndex(18));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.At20PercentSmallerThanAMajorCompetInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseHearingPerformance'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseHearingPerformanceInfo, new RecordItemIndex(19));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseHearingPerformanceInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1907;399.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(20));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1907;399");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1903;580.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(21));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1903;580");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPe'.", repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo, new RecordItemIndex(22));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ARicherBimodalHearingExperience'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ARicherBimodalHearingExperienceInfo, new RecordItemIndex(23));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ARicherBimodalHearingExperienceInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRow'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRowInfo, new RecordItemIndex(24));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRowInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1915;536.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(25));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1915;536");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1918;760.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(26));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1918;760");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.RequestABrochure'.", repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo, new RecordItemIndex(27));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.References'.", repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo, new RecordItemIndex(28));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus1' at 33;65.", repo.CochlearImplantSoundProcessorNucleus1.SelfInfo, new RecordItemIndex(29));
            repo.CochlearImplantSoundProcessorNucleus1.Self.Click("33;65");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(30));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
