///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adult_Slider01 recording.
    /// </summary>
    [TestModule("e4bb4af3-de63-4ec6-bd7e-3442331c83e2", ModuleType.Recording, 1)]
    public partial class Adult_Slider01 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Adult_Slider01 instance = new Adult_Slider01();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adult_Slider01()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adult_Slider01 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult' at 15;8.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Adult.Click("15;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1911;79.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(4));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1911;79");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1904;489.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(5));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1904;489");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPe'.", repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 20;34.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(7));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("20;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 20;34.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(8));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("20;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 20;34.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(9));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("20;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 20;34.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(10));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("20;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 19;34.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(11));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("19;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 19;34.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(12));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("19;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 33;20.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(13));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("33;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 33;20.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(14));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("33;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 33;20.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(15));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("33;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 33;20.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(16));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("33;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 33;20.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(17));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("33;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag' at 6;4.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTagInfo, new RecordItemIndex(18));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag.Click("6;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag1' at 6;8.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag1Info, new RecordItemIndex(19));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag1.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag2' at 4;8.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag2Info, new RecordItemIndex(20));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag2.Click("4;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay' at 15;15.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlayInfo, new RecordItemIndex(21));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay.Click("15;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay' at 8;13.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlayInfo, new RecordItemIndex(22));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay.Click("8;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus1' at 32;69.", repo.CochlearImplantSoundProcessorNucleus1.SelfInfo, new RecordItemIndex(23));
            repo.CochlearImplantSoundProcessorNucleus1.Self.Click("32;69");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(24));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
