///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Parent_Content recording.
    /// </summary>
    [TestModule("fea38604-40c3-4d0f-b746-81171496d6f2", ModuleType.Recording, 1)]
    public partial class Parent_Content : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Parent_Content instance = new Parent_Content();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Parent_Content()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Parent_Content Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent' at 32;8.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Parent.Click("32;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/22a81311-55b3-4d08-8166-4c1ea6846a3f/logo.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-22a81311-55b3-4d08-8166-4c1ea6846a3f-lA0xVqM') on item 'CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConne'.", repo.CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConneInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConneInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/22a81311-55b3-4d08-8166-4c1ea6846a3f/logo.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-22a81311-55b3-4d08-8166-4c1ea6846a3f-lA0xVqM");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.DownloadBrochure'.", repo.CochlearImplantSoundProcessorNucleus.DownloadBrochureInfo, new RecordItemIndex(5));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.DownloadBrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ClinicFinder'.", repo.CochlearImplantSoundProcessorNucleus.ClinicFinderInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ClinicFinderInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(7));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(8));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(9));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/4e5417fe-94fd-44ab-b2ad-38288b434dbd/en_microsite_n7_tagline_hearyourway_1024x177.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-4e5417fe-94fd-44ab-b2ad-38288b434dbd-m157LsM') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConneInfo, new RecordItemIndex(10));
            //Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConneInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/4e5417fe-94fd-44ab-b2ad-38288b434dbd/en_microsite_n7_tagline_hearyourway_1024x177.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-4e5417fe-94fd-44ab-b2ad-38288b434dbd-m157LsM");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.MeetNucleus7TheWorldsFirstAndOnl'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MeetNucleus7TheWorldsFirstAndOnlInfo, new RecordItemIndex(11));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MeetNucleus7TheWorldsFirstAndOnlInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7CombinesProvenHearingPerfor'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7CombinesProvenHearingPerforInfo, new RecordItemIndex(12));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7CombinesProvenHearingPerforInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButton' at 36;22.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButtonInfo, new RecordItemIndex(13));
            repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButton.Click("36;22");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/0d2feb8e-b3a1-430c-a4b2-95603ad0d88c/video_placeholder_overview_video.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-0d2feb8e-b3a1-430c-a4b2-95603ad0d88c-lRhNu92') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne4'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne4Info, new RecordItemIndex(14));
            //Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne4Info, "Src", "http://www.hearyourway.com/wps/wcm/connect/0d2feb8e-b3a1-430c-a4b2-95603ad0d88c/video_placeholder_overview_video.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-0d2feb8e-b3a1-430c-a4b2-95603ad0d88c-lRhNu92");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1907;143.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(15));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1907;143");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1906;259.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(16));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1906;259");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.TheWorldsFirstAndOnlyMadeForIPhon'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TheWorldsFirstAndOnlyMadeForIPhonInfo, new RecordItemIndex(17));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TheWorldsFirstAndOnlyMadeForIPhonInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ThanksToMadeForIPhoneTechnologyWi'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ThanksToMadeForIPhoneTechnologyWiInfo, new RecordItemIndex(18));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ThanksToMadeForIPhoneTechnologyWiInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.YouCanAlsoCheckTheStatusOfTheirD'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.YouCanAlsoCheckTheStatusOfTheirDInfo, new RecordItemIndex(19));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.YouCanAlsoCheckTheStatusOfTheirDInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/a887521d-97cc-4995-b7dd-f3abdf7d4252/made-for-iphone-large.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-a887521d-97cc-4995-b7dd-f3abdf7d4252-lMZjSYY') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.MadeForIPodIPhoneIPad'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MadeForIPodIPhoneIPadInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MadeForIPodIPhoneIPadInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/a887521d-97cc-4995-b7dd-f3abdf7d4252/made-for-iphone-large.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-a887521d-97cc-4995-b7dd-f3abdf7d4252-lMZjSYY");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1909;254.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(21));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1909;254");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1910;342.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(22));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1910;342");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheSmallestAndLightestB'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheSmallestAndLightestBInfo, new RecordItemIndex(23));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheSmallestAndLightestBInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseYourChildsHearingP'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseYourChildsHearingPInfo, new RecordItemIndex(24));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseYourChildsHearingPInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.HearingInNoiseIsTheMostChallenging'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HearingInNoiseIsTheMostChallengingInfo, new RecordItemIndex(25));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HearingInNoiseIsTheMostChallengingInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.FromTheParkToSchoolToANoisyPlayd'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FromTheParkToSchoolToANoisyPlaydInfo, new RecordItemIndex(26));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FromTheParkToSchoolToANoisyPlaydInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1907;352.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(27));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1907;352");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1919;491.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(28));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1919;491");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.AChoiceOfWearingOptionsToFitYour'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.AChoiceOfWearingOptionsToFitYourInfo, new RecordItemIndex(29));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.AChoiceOfWearingOptionsToFitYourInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.AvailableIn6ColourOptionsTheNucle'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.AvailableIn6ColourOptionsTheNucleInfo, new RecordItemIndex(30));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.AvailableIn6ColourOptionsTheNucleInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.FromThePlaygroundToTheSportsField'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FromThePlaygroundToTheSportsFieldInfo, new RecordItemIndex(31));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FromThePlaygroundToTheSportsFieldInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1908;451.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(32));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1908;451");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1903;509.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(33));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1903;509");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/7d484cbc-63eb-45d1-a57b-771128dcba14/N7_Aqua_Device.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-7d484cbc-63eb-45d1-a57b-771128dcba14-lLRX-uw') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.N7AquaPlus'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.N7AquaPlusInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.N7AquaPlusInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/7d484cbc-63eb-45d1-a57b-771128dcba14/N7_Aqua_Device.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-7d484cbc-63eb-45d1-a57b-771128dcba14-lLRX-uw");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.MakeASplashWithAquaPlus'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MakeASplashWithAquaPlusInfo, new RecordItemIndex(35));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MakeASplashWithAquaPlusInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.WithTheHighestWaterResistanceRating'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.WithTheHighestWaterResistanceRatingInfo, new RecordItemIndex(36));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.WithTheHighestWaterResistanceRatingInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTag'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo, new RecordItemIndex(37));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1907;510.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(38));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1907;510");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1903;598.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(39));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1903;598");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRow1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRow1Info, new RecordItemIndex(40));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRow1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1909;606.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(41));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1909;606");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1908;743.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(42));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1908;743");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.RequestABrochure'.", repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo, new RecordItemIndex(43));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1913;754.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(44));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1913;754");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1919;846.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(45));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1919;846");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.References'.", repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo, new RecordItemIndex(46));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.PTagC2017CochlearLtdAllRightsRese'.", repo.CochlearImplantSoundProcessorNucleus.PTagC2017CochlearLtdAllRightsReseInfo, new RecordItemIndex(47));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.PTagC2017CochlearLtdAllRightsReseInfo);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.PTagC2018CochlearLtdAllRightsRese'.", repo.CochlearImplantSoundProcessorNucleus.PTagC2018CochlearLtdAllRightsReseInfo, new RecordItemIndex(48));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.PTagC2018CochlearLtdAllRightsReseInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.CookiePolicy'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.CookiePolicyInfo, new RecordItemIndex(49));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.CookiePolicyInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.PrivacyPolicy'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.PrivacyPolicyInfo, new RecordItemIndex(50));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.PrivacyPolicyInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.TermsOfUse'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.TermsOfUseInfo, new RecordItemIndex(51));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.TermsOfUseInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.ATagBlank'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.ATagBlankInfo, new RecordItemIndex(52));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.ATagBlankInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FollowUsOnSocialMedia'.", repo.CochlearImplantSoundProcessorNucleus.FollowUsOnSocialMediaInfo, new RecordItemIndex(53));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FollowUsOnSocialMediaInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaFacebookFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaFacebookFaSocialCircularInfo, new RecordItemIndex(54));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaFacebookFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaTwitterFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaTwitterFaSocialCircularInfo, new RecordItemIndex(55));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaTwitterFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaYoutubeFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaYoutubeFaSocialCircularInfo, new RecordItemIndex(56));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaYoutubeFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaLinkedinFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaLinkedinFaSocialCircularInfo, new RecordItemIndex(57));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaLinkedinFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnArrowUp' at 26;22.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnArrowUpInfo, new RecordItemIndex(58));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnArrowUp.Click("26;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus1' at 29;67.", repo.CochlearImplantSoundProcessorNucleus1.SelfInfo, new RecordItemIndex(59));
            repo.CochlearImplantSoundProcessorNucleus1.Self.Click("29;67");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus1' at 32;69.", repo.CochlearImplantSoundProcessorNucleus1.SelfInfo, new RecordItemIndex(60));
            repo.CochlearImplantSoundProcessorNucleus1.Self.Click("32;69");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(61));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
