///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Upgrade_Reference recording.
    /// </summary>
    [TestModule("f6481a01-482a-440c-b2d4-f609d4f78de3", ModuleType.Recording, 1)]
    public partial class Upgrade_Reference : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Upgrade_Reference instance = new Upgrade_Reference();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Upgrade_Reference()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Upgrade_Reference Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade' at 50;10.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade.Click("50;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1908;62.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(3));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1908;62");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1919;812.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(4));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1919;812");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.References'.", repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo, new RecordItemIndex(5));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.AppleIncCompatibleHearingDevicesI'.", repo.CochlearImplantSoundProcessorNucleus.AppleIncCompatibleHearingDevicesIInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.AppleIncCompatibleHearingDevicesIInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1190805CP1000Proce'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1190805CP1000ProceInfo, new RecordItemIndex(7));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1190805CP1000ProceInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.MaugerSJWarrenCKnightMGoorevich'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.MaugerSJWarrenCKnightMGoorevichInfo, new RecordItemIndex(8));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.MaugerSJWarrenCKnightMGoorevichInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.TheNucleus7SoundProcessorIsCompati'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.TheNucleus7SoundProcessorIsCompatiInfo, new RecordItemIndex(9));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.TheNucleus7SoundProcessorIsCompatiInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1140877BatteryLife'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1140877BatteryLifeInfo, new RecordItemIndex(10));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1140877BatteryLifeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.WithCompatibleBeltoneOrReSoundHeari'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.WithCompatibleBeltoneOrReSoundHeariInfo, new RecordItemIndex(11));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.WithCompatibleBeltoneOrReSoundHeariInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.HttpsSupportAppleComEnAuHT201466' at 88;3.", repo.CochlearImplantSoundProcessorNucleus.HttpsSupportAppleComEnAuHT201466Info, new RecordItemIndex(12));
            repo.CochlearImplantSoundProcessorNucleus.HttpsSupportAppleComEnAuHT201466.Click("88;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'UseMadeForIPhoneHearingAidsApple' at 1908;660.", repo.UseMadeForIPhoneHearingAidsApple.SelfInfo, new RecordItemIndex(13));
            repo.UseMadeForIPhoneHearingAidsApple.Self.MoveTo("1908;660");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'UseMadeForIPhoneHearingAidsApple' at 1908;633.", repo.UseMadeForIPhoneHearingAidsApple.SelfInfo, new RecordItemIndex(14));
            repo.UseMadeForIPhoneHearingAidsApple.Self.MoveTo("1908;633");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'UseMadeForIPhoneHearingAidsApple.CompatibleHearingDevices'.", repo.UseMadeForIPhoneHearingAidsApple.CompatibleHearingDevicesInfo, new RecordItemIndex(15));
            Validate.Exists(repo.UseMadeForIPhoneHearingAidsApple.CompatibleHearingDevicesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UseMadeForIPhoneHearingAidsApple1' at 485;27.", repo.UseMadeForIPhoneHearingAidsApple1.SelfInfo, new RecordItemIndex(16));
            repo.UseMadeForIPhoneHearingAidsApple1.Self.Click("485;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.References'.", repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo, new RecordItemIndex(17));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UseMadeForIPhoneHearingAidsApple1' at 30;66.", repo.UseMadeForIPhoneHearingAidsApple1.SelfInfo, new RecordItemIndex(18));
            repo.UseMadeForIPhoneHearingAidsApple1.Self.Click("30;66");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(19));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
