///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Header recording.
    /// </summary>
    [TestModule("18433cec-6fed-438e-a51b-e35f22031277", ModuleType.Recording, 1)]
    public partial class Header : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Header instance = new Header();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Header()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Header Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/95a2e3b5-f9f3-4773-a4e7-8ed13128d939/promise.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-95a2e3b5-f9f3-4773-a4e7-8ed13128d939-lvwOml6') on item 'CochlearImplantSoundProcessorNucleus.HearNowAndAlways'.", repo.CochlearImplantSoundProcessorNucleus.HearNowAndAlwaysInfo, new RecordItemIndex(1));
            //Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.HearNowAndAlwaysInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/95a2e3b5-f9f3-4773-a4e7-8ed13128d939/promise.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-95a2e3b5-f9f3-4773-a4e7-8ed13128d939-lvwOml6");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.DownloadBrochure'.", repo.CochlearImplantSoundProcessorNucleus.DownloadBrochureInfo, new RecordItemIndex(2));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.DownloadBrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ClinicFinder'.", repo.CochlearImplantSoundProcessorNucleus.ClinicFinderInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ClinicFinderInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(4));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(5));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/22a81311-55b3-4d08-8166-4c1ea6846a3f/logo.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-22a81311-55b3-4d08-8166-4c1ea6846a3f-lA0xVqM') on item 'CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConne'.", repo.CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConneInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConneInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/22a81311-55b3-4d08-8166-4c1ea6846a3f/logo.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-22a81311-55b3-4d08-8166-4c1ea6846a3f-lA0xVqM");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus1.Element214676384'.", repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info, new RecordItemIndex(8));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus1.Element214676384'.", repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info, new RecordItemIndex(9));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus1.Element214676384'.", repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info, new RecordItemIndex(10));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus1.Element214676384'.", repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info, new RecordItemIndex(11));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus1.Element214676384'.", repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info, new RecordItemIndex(12));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus1.Element214676384'.", repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info, new RecordItemIndex(13));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus1.Element214676384'.", repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info, new RecordItemIndex(14));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus1.Element214676384Info);
            //Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
