///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_Browser recording.
    /// </summary>
    [TestModule("2174494b-8a7b-4f14-bccc-4b3d256b12fd", ModuleType.Recording, 1)]
    public partial class Open_Browser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Open_Browser instance = new Open_Browser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_Browser()
        {
            varEnv = "http://www.hearyourway.com/wps/wcm/connect/uk/n7/home";
            varBrowser = "http://www.hearyourway.com/wps/wcm/connect/uk/n7/home";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_Browser Instance
        {
            get { return instance; }
        }

#region Variables

        string _varEnv;

        /// <summary>
        /// Gets or sets the value of variable varEnv.
        /// </summary>
        [TestVariable("8f837350-a515-4f71-bd1e-83a105433611")]
        public string varEnv
        {
            get { return _varEnv; }
            set { _varEnv = value; }
        }

        string _varBrowser;

        /// <summary>
        /// Gets or sets the value of variable varBrowser.
        /// </summary>
        [TestVariable("8e307589-74df-4c21-9595-fe250297f070")]
        public string varBrowser
        {
            get { return _varBrowser; }
            set { _varBrowser = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $varEnv with browser specified by variable $varBrowser in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser(varEnv, varBrowser, "", false, false, false, false, false);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
