///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Parent_Slider01 recording.
    /// </summary>
    [TestModule("d0e89e46-b7bd-421b-a3bc-c48ce94c8510", ModuleType.Recording, 1)]
    public partial class Parent_Slider01 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Parent_Slider01 instance = new Parent_Slider01();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Parent_Slider01()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Parent_Slider01 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent' at 32;8.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Parent.Click("32;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1911;66.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(4));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1911;66");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1919;673.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(5));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1919;673");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.RequestABrochure'.", repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 30;32.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(7));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("30;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 30;32.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(8));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("30;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 30;32.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(9));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("30;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 30;32.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(10));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("30;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 30;32.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(11));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("30;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1' at 30;32.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1Info, new RecordItemIndex(12));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronLeft1.Click("30;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 32;26.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(13));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("32;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 32;27.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(14));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("32;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 32;27.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(15));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("32;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 32;27.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(16));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("32;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1' at 32;27.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1Info, new RecordItemIndex(17));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.TypcnTypcnChevronRight1.Click("32;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag5' at 8;10.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag5Info, new RecordItemIndex(18));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag5.Click("8;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag1' at 10;8.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag1Info, new RecordItemIndex(19));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag1.Click("10;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag3' at 9;11.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag3Info, new RecordItemIndex(20));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag3.Click("9;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag5' at 6;13.", repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag5Info, new RecordItemIndex(21));
            repo.CochlearImplantSoundProcessorNucleus.CarouselIndicators.SomeLiTag5.Click("6;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselVideo.BtnPlay1' at 59;86.", repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.BtnPlay1Info, new RecordItemIndex(22));
            repo.CochlearImplantSoundProcessorNucleus.CarouselVideo.BtnPlay1.Click("59;86");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus'.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(23));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus' at 939;483.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(24));
            repo.CochlearImplantSoundProcessorNucleus.Self.Click("939;483");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus1' at 25;66.", repo.CochlearImplantSoundProcessorNucleus1.SelfInfo, new RecordItemIndex(25));
            repo.CochlearImplantSoundProcessorNucleus1.Self.Click("25;66");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(26));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
