///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Upgrade_Content recording.
    /// </summary>
    [TestModule("3d8aff78-7a85-4e39-b5e5-d681cd9c8cdf", ModuleType.Recording, 1)]
    public partial class Upgrade_Content : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Upgrade_Content instance = new Upgrade_Content();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Upgrade_Content()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Upgrade_Content Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade' at 29;5.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade.Click("29;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/22a81311-55b3-4d08-8166-4c1ea6846a3f/logo.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-22a81311-55b3-4d08-8166-4c1ea6846a3f-lA0xVqM') on item 'CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConne'.", repo.CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConneInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.HttpWwwHearyourwayComWpsWcmConneInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/22a81311-55b3-4d08-8166-4c1ea6846a3f/logo.svg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-22a81311-55b3-4d08-8166-4c1ea6846a3f-lA0xVqM");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.DownloadBrochure'.", repo.CochlearImplantSoundProcessorNucleus.DownloadBrochureInfo, new RecordItemIndex(5));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.DownloadBrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ClinicFinder'.", repo.CochlearImplantSoundProcessorNucleus.ClinicFinderInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ClinicFinderInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Adult'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo, new RecordItemIndex(7));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.AdultInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Parent'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo, new RecordItemIndex(8));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.ParentInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(9));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/4e5417fe-94fd-44ab-b2ad-38288b434dbd/en_microsite_n7_tagline_hearyourway_1024x177.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-4e5417fe-94fd-44ab-b2ad-38288b434dbd-m157LsM') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConneInfo, new RecordItemIndex(10));
            //Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConneInfo, "Src", "http://www.hearyourway.com/wps/wcm/connect/4e5417fe-94fd-44ab-b2ad-38288b434dbd/en_microsite_n7_tagline_hearyourway_1024x177.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-4e5417fe-94fd-44ab-b2ad-38288b434dbd-m157LsM");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.UpgradeToNucleus7TheWorldsFirst'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.UpgradeToNucleus7TheWorldsFirstInfo, new RecordItemIndex(11));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.UpgradeToNucleus7TheWorldsFirstInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.OurSmallestAndLightestBehindTheEar'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.OurSmallestAndLightestBehindTheEarInfo, new RecordItemIndex(12));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.OurSmallestAndLightestBehindTheEarInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButton' at 32;22.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButtonInfo, new RecordItemIndex(13));
            repo.CochlearImplantSoundProcessorNucleus.FluidContainer.FaFaAngleDownButton.Click("32;22");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/0d2feb8e-b3a1-430c-a4b2-95603ad0d88c/video_placeholder_overview_video.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-0d2feb8e-b3a1-430c-a4b2-95603ad0d88c-lRhNu92') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne4'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne4Info, new RecordItemIndex(14));
            //Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.HttpWwwHearyourwayComWpsWcmConne4Info, "Src", "http://www.hearyourway.com/wps/wcm/connect/0d2feb8e-b3a1-430c-a4b2-95603ad0d88c/video_placeholder_overview_video.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE-0d2feb8e-b3a1-430c-a4b2-95603ad0d88c-lRhNu92");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1906;139.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(15));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1906;139");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1919;226.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(16));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1919;226");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.LookingToUpgrade'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.LookingToUpgradeInfo, new RecordItemIndex(17));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.LookingToUpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.WhetherYouPreferABehindTheEarOrA'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.WhetherYouPreferABehindTheEarOrAInfo, new RecordItemIndex(18));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.WhetherYouPreferABehindTheEarOrAInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.COMPARENUCLEUS7TOYOURSOUNDPROCESSO'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.COMPARENUCLEUS7TOYOURSOUNDPROCESSOInfo, new RecordItemIndex(19));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.COMPARENUCLEUS7TOYOURSOUNDPROCESSOInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInforma'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInformaInfo, new RecordItemIndex(20));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInformaInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.COMPARENUCLEUS7TOYOURSOUNDPROCESSO' at 159;26.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.COMPARENUCLEUS7TOYOURSOUNDPROCESSOInfo, new RecordItemIndex(21));
            repo.CochlearImplantSoundProcessorNucleus.FluidContainer.COMPARENUCLEUS7TOYOURSOUNDPROCESSO.Click("159;26");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearHearingImplantsCochlearUni.SoundProcessorComparison'.", repo.CochlearHearingImplantsCochlearUni.SoundProcessorComparisonInfo, new RecordItemIndex(22));
            //Validate.Exists(repo.CochlearHearingImplantsCochlearUni.SoundProcessorComparisonInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UpgradeToCochlearImplantSoundProces' at 486;26.", repo.UpgradeToCochlearImplantSoundProces.SelfInfo, new RecordItemIndex(23));
            //repo.UpgradeToCochlearImplantSoundProces.Self.Click("486;26");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearHearingImplantsCochlearUni.SoundProcessorComparison'.", repo.CochlearHearingImplantsCochlearUni.SoundProcessorComparisonInfo, new RecordItemIndex(24));
            Validate.Exists(repo.CochlearHearingImplantsCochlearUni.SoundProcessorComparisonInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SoundProcessorComparisonGoogleChro' at 485;28.", repo.SoundProcessorComparisonGoogleChro.SelfInfo, new RecordItemIndex(25));
            repo.SoundProcessorComparisonGoogleChro.Self.Click("485;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInforma'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInformaInfo, new RecordItemIndex(26));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInformaInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInforma' at 146;9.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInformaInfo, new RecordItemIndex(27));
            repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ATagRegisterToReceiveUpgradeInforma.Click("146;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.RequestABrochure'.", repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo, new RecordItemIndex(28));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UpgradeToCochlearImplantSoundProces' at 28;65.", repo.UpgradeToCochlearImplantSoundProces.SelfInfo, new RecordItemIndex(29));
            repo.UpgradeToCochlearImplantSoundProces.Self.Click("28;65");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheWorldsFirstAndOnlyM1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheWorldsFirstAndOnlyM1Info, new RecordItemIndex(30));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheWorldsFirstAndOnlyM1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ThanksToMadeForIPhoneCompatibility'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ThanksToMadeForIPhoneCompatibilityInfo, new RecordItemIndex(31));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ThanksToMadeForIPhoneCompatibilityInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://www.hearyourway.com/wps/wcm/connect/a887521d-97cc-4995-b7dd-f3abdf7d4252/made-for-iphone-large.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-a887521d-97cc-4995-b7dd-f3abdf7d4252-lMZjSYY') on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.MadeForIPodIPhoneIPad1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MadeForIPodIPhoneIPad1Info, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.MadeForIPodIPhoneIPad1Info, "Src", "http://www.hearyourway.com/wps/wcm/connect/a887521d-97cc-4995-b7dd-f3abdf7d4252/made-for-iphone-large.png?MOD=AJPERES&CACHEID=ROOTWORKSPACE-a887521d-97cc-4995-b7dd-f3abdf7d4252-lMZjSYY");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1906;214.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(33));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1906;214");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1915;322.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(34));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1915;322");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartAppInfo, new RecordItemIndex(35));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartAppInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTag'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo, new RecordItemIndex(36));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTag'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo, new RecordItemIndex(37));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheApp'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo, new RecordItemIndex(38));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheApp'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo, new RecordItemIndex(39));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheApp' at 106;20.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheAppInfo, new RecordItemIndex(40));
            //repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DownloadTheApp.Click("106;20");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearHearingImplantsCochlearUni.SpanTagNucleu'.", repo.CochlearHearingImplantsCochlearUni.SpanTagNucleuInfo, new RecordItemIndex(41));
            //Validate.Exists(repo.CochlearHearingImplantsCochlearUni.SpanTagNucleuInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TheNucleusRSmartAppInteractiveDemo' at 487;27.", repo.TheNucleusRSmartAppInteractiveDemo.SelfInfo, new RecordItemIndex(42));
            //repo.TheNucleusRSmartAppInteractiveDemo.Self.Click("487;27");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FindYourProcessor'.", repo.CochlearImplantSoundProcessorNucleus.FindYourProcessorInfo, new RecordItemIndex(43));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FindYourProcessorInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.CheckSoundProcessorStatus'.", repo.CochlearImplantSoundProcessorNucleus.CheckSoundProcessorStatusInfo, new RecordItemIndex(44));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.CheckSoundProcessorStatusInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheSmallestAndLightestB1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheSmallestAndLightestB1Info, new RecordItemIndex(45));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.Nucleus7IsTheSmallestAndLightestB1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1906;321.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(46));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1906;321");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1911;418.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(47));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1911;418");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.At25PercentSmallerAnd24PercentLight'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.At25PercentSmallerAnd24PercentLightInfo, new RecordItemIndex(48));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.At25PercentSmallerAnd24PercentLightInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.AndThanksToNewChipTechnologyYouC'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.AndThanksToNewChipTechnologyYouCInfo, new RecordItemIndex(49));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.AndThanksToNewChipTechnologyYouCInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseHearingPerformance1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseHearingPerformance1Info, new RecordItemIndex(50));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ProvenToOptimiseHearingPerformance1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTag'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo, new RecordItemIndex(51));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTag'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo, new RecordItemIndex(52));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SomePTagInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1906;397.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(53));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1906;397");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1913;486.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(54));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1913;486");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPe'.", repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo, new RecordItemIndex(55));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1911;502.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(56));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1911;502");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1907;593.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(57));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1907;593");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.ARicherBimodalHearingExperience1'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ARicherBimodalHearingExperience1Info, new RecordItemIndex(58));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.ARicherBimodalHearingExperience1Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.WithANucleus7SoundProcessorAndAC'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.WithANucleus7SoundProcessorAndACInfo, new RecordItemIndex(59));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.WithANucleus7SoundProcessorAndACInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRow2'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRow2Info, new RecordItemIndex(60));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.DivTagRow2Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1904;563.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(61));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1904;563");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1916;741.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(62));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1916;741");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.RequestABrochure'.", repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo, new RecordItemIndex(63));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.RequestABrochureInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1908;740.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(64));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1908;740");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1916;806.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(65));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1916;806");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.References'.", repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo, new RecordItemIndex(66));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ReferencesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.AppleIncCompatibleHearingDevicesI'.", repo.CochlearImplantSoundProcessorNucleus.AppleIncCompatibleHearingDevicesIInfo, new RecordItemIndex(67));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.AppleIncCompatibleHearingDevicesIInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1190805CP1000Proce'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1190805CP1000ProceInfo, new RecordItemIndex(68));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1190805CP1000ProceInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.MaugerSJWarrenCKnightMGoorevich'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.MaugerSJWarrenCKnightMGoorevichInfo, new RecordItemIndex(69));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.MaugerSJWarrenCKnightMGoorevichInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.TheNucleus7SoundProcessorIsCompati'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.TheNucleus7SoundProcessorIsCompatiInfo, new RecordItemIndex(70));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.TheNucleus7SoundProcessorIsCompatiInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1140877BatteryLife'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1140877BatteryLifeInfo, new RecordItemIndex(71));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.CochlearLimitedD1140877BatteryLifeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.SomeUlTag.WithCompatibleBeltoneOrReSoundHeari'.", repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.WithCompatibleBeltoneOrReSoundHeariInfo, new RecordItemIndex(72));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.SomeUlTag.WithCompatibleBeltoneOrReSoundHeariInfo);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.PTagC2017CochlearLtdAllRightsRese'.", repo.CochlearImplantSoundProcessorNucleus.PTagC2017CochlearLtdAllRightsReseInfo, new RecordItemIndex(73));
            //Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.PTagC2017CochlearLtdAllRightsReseInfo);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.PTagC2018CochlearLtdAllRightsRese'.", repo.CochlearImplantSoundProcessorNucleus.PTagC2018CochlearLtdAllRightsReseInfo, new RecordItemIndex(74));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.PTagC2018CochlearLtdAllRightsReseInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.CookiePolicy'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.CookiePolicyInfo, new RecordItemIndex(75));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.CookiePolicyInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.SomeLiTag'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.SomeLiTagInfo, new RecordItemIndex(76));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.SomeLiTagInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.TermsOfUse'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.TermsOfUseInfo, new RecordItemIndex(77));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.TermsOfUseInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.ATagBlank'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.ATagBlankInfo, new RecordItemIndex(78));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledFooterLinks.ATagBlankInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FollowUsOnSocialMedia'.", repo.CochlearImplantSoundProcessorNucleus.FollowUsOnSocialMediaInfo, new RecordItemIndex(79));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FollowUsOnSocialMediaInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaFacebookFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaFacebookFaSocialCircularInfo, new RecordItemIndex(80));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaFacebookFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaTwitterFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaTwitterFaSocialCircularInfo, new RecordItemIndex(81));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaTwitterFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaYoutubeFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaYoutubeFaSocialCircularInfo, new RecordItemIndex(82));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaYoutubeFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaLinkedinFaSocialCircular'.", repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaLinkedinFaSocialCircularInfo, new RecordItemIndex(83));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.ListInlineListUnstyledSocialLinks.FaFaLinkedinFaSocialCircularInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnArrowUp' at 17;25.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnArrowUpInfo, new RecordItemIndex(84));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnArrowUp.Click("17;25");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TheNucleusRSmartAppInteractiveDemo' at 28;60.", repo.TheNucleusRSmartAppInteractiveDemo.SelfInfo, new RecordItemIndex(85));
            //repo.TheNucleusRSmartAppInteractiveDemo.Self.Click("28;60");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TheNucleusRSmartAppInteractiveDemo' at 29;68.", repo.TheNucleusRSmartAppInteractiveDemo.SelfInfo, new RecordItemIndex(86));
            //repo.TheNucleusRSmartAppInteractiveDemo.Self.Click("29;68");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(87));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
