///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Upgrade_Slider01 recording.
    /// </summary>
    [TestModule("0df11043-45c6-4983-813c-b93481a4ce6f", ModuleType.Recording, 1)]
    public partial class Upgrade_Slider01 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Upgrade_Slider01 instance = new Upgrade_Slider01();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Upgrade_Slider01()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Upgrade_Slider01 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade' at 36;13.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade.Click("36;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1908;53.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(4));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1908;53");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1912;483.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(5));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1912;483");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPe'.", repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.StrongTag6ColourOptionsToFitYourPeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 35;27.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(7));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("35;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 35;27.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(8));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("35;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 35;27.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(9));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("35;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 35;27.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(10));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("35;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 35;27.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(11));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("35;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 30;27.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(12));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("30;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft' at 30;27.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeftInfo, new RecordItemIndex(13));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronLeft.Click("30;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 27;25.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(14));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("27;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 27;25.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(15));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("27;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 27;25.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(16));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("27;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 27;25.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(17));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("27;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 27;25.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(18));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("27;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight' at 27;25.", repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRightInfo, new RecordItemIndex(19));
            repo.CochlearImplantSoundProcessorNucleus.TypcnTypcnChevronRight.Click("27;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag' at 8;7.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTagInfo, new RecordItemIndex(20));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag1' at 6;9.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag1Info, new RecordItemIndex(21));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag1.Click("6;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag2' at 8;6.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag2Info, new RecordItemIndex(22));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag2.Click("8;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay' at 12;12.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlayInfo, new RecordItemIndex(23));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay.Click("12;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag3' at 7;5.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag3Info, new RecordItemIndex(24));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.SomeLiTag3.Click("7;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay' at 10;12.", repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlayInfo, new RecordItemIndex(25));
            repo.CochlearImplantSoundProcessorNucleus.CarouselImage.PausePlay.Click("10;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UpgradeToCochlearImplantSoundProces' at 26;67.", repo.UpgradeToCochlearImplantSoundProces.SelfInfo, new RecordItemIndex(26));
            repo.UpgradeToCochlearImplantSoundProces.Self.Click("26;67");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(27));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
