///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N7UK
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Upgrade recording.
    /// </summary>
    [TestModule("b6db14d5-5921-4787-817b-9b3d64aa48ec", ModuleType.Recording, 1)]
    public partial class Upgrade : ITestModule
    {
        /// <summary>
        /// Holds an instance of the N7UKRepository repository.
        /// </summary>
        public static N7UKRepository repo = N7UKRepository.Instance;

        static Upgrade instance = new Upgrade();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Upgrade()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Upgrade Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.hearyourway.com/wps/wcm/connect/uk/n7/home' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            //Host.Current.OpenBrowser("http://www.hearyourway.com/wps/wcm/connect/uk/n7/home", "chrome", "", false, false, false, false, false);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(1));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade' at 44;11.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(2));
            repo.CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade.Click("44;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(3));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1909;89.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(4));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1909;89");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1911;340.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(5));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1911;340");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartAppInfo, new RecordItemIndex(6));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartAppInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UpgradeToCochlearImplantSoundProces' at 37;71.", repo.UpgradeToCochlearImplantSoundProces.SelfInfo, new RecordItemIndex(7));
            repo.UpgradeToCochlearImplantSoundProces.Self.Click("37;71");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(8));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1911;136.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(9));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1911;136");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1905;393.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(10));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1905;393");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.SpanTagUpgrade'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SpanTagUpgradeInfo, new RecordItemIndex(11));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SpanTagUpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CochlearImplantSoundProcessorNucleus.FluidContainer.SpanTagUpgrade' at 133;19.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SpanTagUpgradeInfo, new RecordItemIndex(12));
            repo.CochlearImplantSoundProcessorNucleus.FluidContainer.SpanTagUpgrade.Click("133;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(13));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'CochlearImplantSoundProcessorNucleus' at 1913;94.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(14));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1913;94");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'CochlearImplantSoundProcessorNucleus' at 1909;358.", repo.CochlearImplantSoundProcessorNucleus.SelfInfo, new RecordItemIndex(15));
            repo.CochlearImplantSoundProcessorNucleus.Self.MoveTo("1909;358");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartApp'.", repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartAppInfo, new RecordItemIndex(16));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.FluidContainer.TakeControlWithTheNucleusSmartAppInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UpgradeToCochlearImplantSoundProces' at 31;68.", repo.UpgradeToCochlearImplantSoundProces.SelfInfo, new RecordItemIndex(17));
            repo.UpgradeToCochlearImplantSoundProces.Self.Click("31;68");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CochlearImplantSoundProcessorNucleus.UtilityNav.Upgrade'.", repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo, new RecordItemIndex(18));
            Validate.Exists(repo.CochlearImplantSoundProcessorNucleus.UtilityNav.UpgradeInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
